FROM openjdk:11.0.15
ARG APP_THREAD_COUNT
ENV APP_THREAD_COUNT=$APP_THREAD_COUNT
ARG KAFKA_BOOTSTRAP_SERVERS
ENV KAFKA_BOOTSTRAP_SERVERS=$KAFKA_BOOTSTRAP_SERVERS
ARG KAFKA_BOOTSTRAP_SERVERS_PORT
ENV KAKFA_BOOTSTRAP_SERVERS_PORT=$KAFKA_BOOTSTRAP_SERVERS_PORT
ARG KAFKA_TOPIC_NAME
ENV KAFKA_TOPIC_NAME=$KAFKA_TOPIC_NAME
ARG KAFKA_CONSUMER_GROUP
ENV KAFKA_CONSUMER_GROUP=$KAFKA_CONSUMER_GROUP
ARG DB_URL
ENV DB_URL=$DB_URL
ARG DB_PORT
ENV DB_PORT=$DB_PORT
ARG DB_NAME
ENV DB_NAME=$DB_NAME
ARG DB_USER
ENV DB_USER=$DB_USER
ARG DB_PASSWORD
ENV DB_PASSWORD=$DB_PASSWORD
ARG DB_SCHEMA
ENV DB_SCHEMA=$DB_SCHEMA

COPY . ./app

WORKDIR ./app
RUN chmod +x gradlew && ./gradlew build
WORKDIR ./build/libs/
ENTRYPOINT ["java", "-jar", "message-consumer-0.0.1-SNAPSHOT.jar"]