CREATE TABLE telemetries
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    agent_id       VARCHAR(255),
    active_service VARCHAR(255),
    quality_score  INTEGER,
    CONSTRAINT pk_telemetries PRIMARY KEY (id),
    CONSTRAINT fk_telemetries_on_agent FOREIGN KEY (agent_id) REFERENCES agents (agent_id) ON DELETE cascade ON UPDATE cascade
);